(define (problem stage_lights)
(:domain stage_lights)
    ;; This is a sample problem with 5 lights
    (:objects
        light_1 light_2 light_3 light_4 light_5 light_6 light_7 light_8 light_9 light_10 light_0 - light
    )
    ;; Initial state of the lights
    (:init
        (left light_1 light_2)
        (right light_2 light_1)
        (left light_2 light_3)
        (right light_3 light_2)
        (left light_3 light_4)
        (right light_4 light_3)        
        (left light_4 light_5)
        (right light_5 light_4)        
        (left light_5 light_6)
        (right light_6 light_5)        
        (left light_6 light_7)
        (right light_7 light_6)        
        (left light_7 light_8)
        (right light_8 light_7)   
        (left light_8 light_9)
        (right light_9 light_8)   
        (left light_9 light_10)
        (right light_10 light_9)

        (on light_1)
        (off light_2)
        (on light_3)
        (off light_4)
        (off light_5)
        (on light_6)
        (off light_7)
        (off light_8)
        (on light_9)
        (off light_10)
        
        (left light_10 light_0)
        (right light_0 light_10)
        (right light_1 light_0)
        (left light_0 light_1)
        (off light_0)
    )
    
    (:goal (and
        ;; Turn on all 10 lights
        (on light_1)
        (on light_2)
        (on light_3)
        (on light_4)
        (on light_5)
        (on light_6)
        (on light_7)
        (on light_8)
        (on light_9)
        (on light_10)
    ))
)