(define (problem stage_lights)
(:domain stage_lights)
    ;; This is a sample problem with 5 lights
    (:objects
        light_1 light_2 light_3 light_4 light_5 light_6 light_7 light_8 light_9 light_10 - light
    )
    ;; Initial state of the lights
    (:init
        (left_off light_1)
        (on light_1)
        (right_off light_1)
        (left_on light_2)
        (off light_2)
        (right_on light_2)
        (left_off light_3)
        (on light_3)
        (right_off light_3)
        (left_on light_4)
        (off light_4)
        (right_off light_4)
        (left_off light_5)
        (off light_5)
        (right_on light_5)
        (left_off light_6)
        (on light_6)
        (right_off light_6)
        (left_on light_7)
        (off light_7)
        (right_off light_7)
        (left_off light_8)
        (off light_8)
        (right_on light_8)
        (left_off light_9)
        (on light_9)
        (right_off light_9)
        (left_on light_10)
        (off light_10)
        (right_off light_10)
    )
    
    (:goal (and
        ;; Turn on all 10 lights
        (on light_1)
        (on light_2)
        (on light_3)
        (on light_4)
        (on light_5)
        (on light_6)
        (on light_7)
        (on light_8)
        (on light_9)
        (on light_10)
    ))
)